src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lead_generator.urls', namespace='lead_generator')),
    path('users/', include('users.urls', namespace='users')),
]

src/lead_generator/urls.py
from django.urls import path
from .views import *

app_name = 'lead_generator'

urlpatterns = [
    path('', MainView.as_view(), name='lead_generator'),
    path('leads/', ListLeadsView.as_view(), name='leads')
]

src/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('sign-up/', UserSignUpView.as_view(), name='signup'),
    path('update/<pk>/', UserUpdateView.as_view(), name='update'),
]

src/lead_generator/models.py
from django.contrib.auth.models import User
from django.db import models


class Lead(models.Model):
    name = models.CharField(max_length=255, verbose_name='Lead name', unique=True)
    address = models.CharField(max_length=1028, verbose_name='Address')
    phone_number = models.CharField(max_length=16, verbose_name='Phone number', blank=True, null=True)
    url = models.URLField(verbose_name='URL', blank=True, null=True)
    keyword = models.CharField(max_length=255, verbose_name='Keyword',
                               blank=True, null=True)
    location = models.CharField(max_length=255, verbose_name='Location',
                                blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Lead'
        verbose_name_plural = 'Leads'
        ordering = ['-created_at']

src/lead_generator/forms.py
from django import forms


class LeadForm(forms.Form):
    keywords = forms.CharField(label='Keywords', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Example: Restaurant, Hotel'}))
    location = forms.CharField(label='Location', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Example: San Francisco'}))

src/lead_generator/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from users.forms import UserUpdateForm
from .models import Lead
from django.contrib.auth import get_user_model

__all__ = (
    'MainView',
    'ListLeadsView'
)

User = get_user_model()


class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'lead_generator/lead_generator.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, 'You are not authenticated')
            return HttpResponseRedirect(reverse_lazy('users:login'))

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['update_form'] = UserUpdateForm(instance=self.request.user)

        return context


class ListLeadsView(LoginRequiredMixin, ListView):
    model = Lead
    template_name = 'lead_generator/list_leads.html'
    paginate_by = 10

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, 'You are not authenticated')
            return HttpResponseRedirect(reverse_lazy('users:login'))

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user_parameters = User.objects.filter(username=self.request.user.username,
                                              is_active=True).values().first()
        keyword = user_parameters.get('keyword')
        location = user_parameters.get('location')
        queryset = Lead.objects.filter(keyword=keyword, location=location)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        count = self.request.GET.get('value')
        context['all_leads'] = self.get_queryset()[:count]
        return context

src/lead_generator/templates/lead_generator/lead_generator.html
{% extends 'base.html' %}

{% block title %}Lead Generator{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6 mx-auto">

        <div class="card shadow">
                <div class="card-body">
                <h5 class="card-text text-center font-italic">Update form User</h5>
                    <form action="{% url 'users:update' user.pk %}" method="post">
                        {% csrf_token %}
                        {% for field in update_form %}
                            <div class="fieldWrapper">
                            {% if field.errors %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            {% endif %}
                                {{ field.label_tag }} {{ field }}
                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <input class="btn btn-info mt-3" type="submit" value="Update">

                    </form>
                </div>
            </div>

            <div class="card shadow mt-4">
                <div class="card-body">
                <h5 class="card-text text-center font-italic">Lead Generator</h5>
                    <form action="{% url 'lead_generator:leads' %}">
                        {% if user.keyword and user.location %}
                            <select class="form-select" aria-label="Default select example">
                                <option selected>How many leads to generate</option>
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                            </select>
                            <input class="btn btn-info mt-3" type="submit" value="Submit">
                        {% else %}
                            <div>
                                <h6 class="form-control-plaintext text-center">
                                    Enter your keyword and location in the form above
                                </h6>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

src/lead_generator/templates/lead_generator/list_leads.html
{% extends 'base.html' %}

{% block title %}Список Маршрутов{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-10 mx-auto">
           <div class="card shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th colspan="6">
                                <h5 class="font-italic text-center">List of generated leads by parameters: {{ user.keyword }}, {{ user.location }}</h5>
                            </th>
                        </tr>
                        <tr class="table-primary">
                            <th>Name Lead</th>
                            <th>Address Lead</th>
                            <th>Phone number Lead</th>
                            <th>Url Lead</th>
                        </tr>
                        </thead>

                        {% for lead in all_leads %}
                            <tr>
                                <td>{{ lead.name }}</td>
                                <td>{{ lead.address }}</td>
                                <td>{{ lead.phone_number }}</td>
                                <td>{{ lead.url }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>

                <nav aria-label="Page navigation" class="d-flex justify-content-center">
                    <ul class="pagination">
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span></a>
                            {% endif %}

                        </li>
                        {% for page in page_obj.paginator.page_range %}
                            <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                                <a class="page-link " href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endfor %}

                        <li class="page-item">
                            {% if page_obj.has_next %}
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;</span>
                            {% endif %}
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
        </div>
    </div>
{% endblock %}