src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lead_generator.urls', namespace='lead_generator')),
    path('users/', include('users.urls', namespace='users')),
]

src/lead_generator/urls.py
from django.urls import path
from .views import *

app_name = 'lead_generator'

urlpatterns = [
    path('', MainView.as_view(), name='lead_generator'),
    path('leads/', ListLeadsView.as_view(), name='leads')
]

src/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('sign-up/', UserSignUpView.as_view(), name='signup'),
    path('update/<pk>/', UserUpdateView.as_view(), name='update'),
]

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous">
      <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
  <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'lead_generator:lead_generator' %}">Lead-Generator App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navbarNav" aria-controls="navbarNav"
                  aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                  {% if request.user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'users:logout' %}">
                              Log-out
                          </a>
                      </li>
                  {% else %}
                      <li class="nav-item active">
                          <a class="nav-link" href="{% url 'users:login' %}">Log-in</a>
                      </li>
                      <li class="nav-item active">
                          <a class="nav-link" href="{% url 'users:signup' %}">Sign-up</a>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </nav>
  </div>

  <div class="container">
      <div class="row">
          <div class="col-md-6 mx-auto mt-3">
              {% if messages %}
                  {% for message in messages %}
                      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                          <div class="alert alert-warning alert-dismissible fade show" role="alert">
                              <span class="d-flex justify-content-center">{{ message }}</span>
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                      {% else %}
                          <div class="alert alert-success alert-dismissible fade show" role="alert">
                              <span class="d-flex justify-content-center">{{ message }}</span>
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                      {% endif %}
                  {% endfor %}
              {% endif %}
          </div>
      </div>
      <div class="container bg-light py-5">
          {% block content %}
          {% endblock %}
      </div>
      <footer>
          <div class="container bg-dark py-5">
              <h4 class="font-italic text-center text-white">Lead-Generator App</h4>
              <p class="text-center text-white">Lead generation service</p>
          </div>
          <div class="container bg-secondary py-3">
              <h6 class="text-white">All rights to wear &copy; <span class="text-info">Lead-Generator App</span></h6>
          </div>
      </footer>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
          integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
  </script>
  <script src="https://code.jquery.com/jquery-3.6.3.slim.min.js"
          integrity="sha256-ZwqZIVdD3iXNyGHbSYdsmWP//UBokj2FHAxKuSBKDSo=" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
          integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
  </script>


  </body>
</html>>